### PR TITLE
update README and bump up package versions

### PR DESCRIPTION
**Pull request by arunkarnati**

### CODE REVIEW

**Comment by efjacobson** [comment]
@arunkarnati if you want to further consolidate the steps, `npm install @acme/schemas --no-save` installs deps from package and also the inline one

**Comment by arunkarnati** [comment]
> @arunkarnati if you want to further consolidate the steps, `npm install @acme/schemas --no-save` installs deps from package and also the inline one
@efjacobson - not sure what you meant by this?

**Comment by efjacobson** [comment]
@arunkarnati you can combine 2 steps into 1

```
npm install && npm install @acme/schemas --no-save
```

does the same thing as

```
npm install @acme/schemas --no-save
```

**Comment by efjacobson** [comment]
@arunkarnati but also it doesnt matter, change it or leave it up to you

**Comment by arunkarnati** [comment]
@efjacobson - let's keep it simple and easy to understand.

**Pull request merged**
